# Orb 'circleci/gradle@2.2.0' resolved to 'circleci/gradle@2.2.0'
version: 2.1

executors:
  jdk:
    docker:
      - image: cimg/openjdk:13.0

commands:
  setup:
    steps:
      - checkout

      - run:
          command: find . -name 'build.gradle' | sort | xargs cat | shasum | awk '{print $1}' > /tmp/gradle_cache_seed
          name: Generate Cache Checksum

      - restore_cache:
          key: gradle-v1-{{ checksum "/tmp/gradle_cache_seed" }}-{{ checksum ".circleci/config.yml" }}

  teardown:
    steps:
      - save_cache:
          key: gradle-v1-{{ checksum "/tmp/gradle_cache_seed" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

jobs:
  build:
    executor: jdk
    steps:
      - setup

      - run:
          name: Build jars
          command: |
            ./gradlew sourcesJar
            ./gradlew shadowJar

      - teardown

      - store_artifacts:
          path: ./exporters/trace/build
      - store_artifacts:
          path: ./exporters/metrics/build
      - store_artifacts:
          path: ./exporters/auto/build
  style:
    executor: jdk
    steps:
      - setup

      - run:
          name: SpotlessCheck
          command: ./gradlew spotlessCheck

      - teardown
  test:
    executor: jdk
    steps:
      - setup_remote_docker:
        version: 19.03.13
      - setup
      - run:
          cache_checksum_file: build.gradle
          cache_key: v1
          command: ./gradlew test
          name: Run Tests
          working_directory: ''

      - teardown

      - store_test_results:
          path: .

      - store_artifacts:
          path: /home/circleci/project/exporters/trace/build/reports/jacoco/test

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test
      - style
